### PR TITLE
Full website with router

### PR DESCRIPTION
**Pull request by rbanos-mv**
# Math magicians
"Math magicians" is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to: (1) Make simple calculations. (2) Read a random math-related quote.

## This PR (Full website with router) includes the following requirements:
- Create a website consisting of 3 pages: Home, Calculator, and Quote.
- The general layout should match these wireframes:

<p align="center">
  Core elements
  Core elements
  Core elements
</p>

- Add your own styles to improve the look and feel.
- In this project, you should use React basic styling.
- For every page, you should create a route.
- Make sure that navigation links for all 3 routes are displayed on each page.
- Use React Router to make the routes work.

## Previous requirements (refactor with hooks)
- Refactor the Calculator component (`components/Calculator.js`) from a class based component to a functional component with hooks.
- Keep the same functionality.
 

## Previous requirements (events)

- Copy the files `calculate.js` and `operate.js` into a logic/ directory in your project.
- Analyze the files `calculate.js` and `operate.js`, be sure you understand what they do.
- Add `big.js` as dependency.
- Import the files in your `Calculator` component.
- Implement the event handlers you need to use the math logic from `calculate.js` and `operate.js` in your React component.
- Practice what you have learned until now: use state and props, pass props to child components, use lifecycle methods, lift state up.
- Test your app in the browser. It should be able to perform math operations.

## Previous requirements (components)
- Delete all the boilerplate from CRA (text, images, styles).
- Create a directory called `components`.
- Inside components, create a new `Calculator.js` file.
- In `Calculator.js`, create a React component that matches this design:

<p align="center">
  Calculator
</p>

- Don't add any extra design.
- Develop just the UI of the calculator.
- Use class based components (All components should be class-based).
- Once the Calculator is ready, import it and use it in your main component (App.js).
- Test it in the browser; it should render without problems.

### General requirements
- Make sure that there are no linter errors.
- Make sure that you used correct Gitflow.
- Make sure that you documented your work in a professional way.
### JavaScript requirements
- Follow our list of best practices for JavaScript.
### Project requirements
- Create a React application using Create React App (CRA).
- The application should run in the browser without errors.

### CODE REVIEW

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @rbanos-mv, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

giphy

Cheers and Happy coding!👏👏👏

## Optional: You don't need line number 3 and 4 on the readme, kindly remove them.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rbanos-mv** [comment]
@sja-thedude
I'm afraid the _reason_ for the optional suggestion is missing. I have included those lines in most of my previous projects, and never before I received such suggestion. Maybe no other code reviewer read it, or maybe it is not included in the rubrics, I don't know.

Would you please explain what's wrong with lines 3 and 4 of the README file? I would like to learn a good _reason_ to remove them. It is not 100% clear to me.

**Comment by sja-thedude** [comment]
> @sja-thedude I'm afraid the _reason_ for the optional suggestion is missing. I have included those lines in most of my previous projects, and never before I received such suggestion. Maybe no other code reviewer read it, or maybe it is not included in the rubrics, I don't know.
> 
> Would you please explain what's wrong with lines 3 and 4 of the README file? I would like to learn a good _reason_ to remove them. It is not 100% clear to me.

@rbanos-mv Line 3 and 4 of the readme is your intro which is not required for the readme of your project. Only project description should be in your project mainly and not about your introduction. The introduction will be in your Github readme in the coming days where you will set up a good GitHub profile but projects dont contain your intro.

**Comment by rbanos-mv** [comment]
Thank you @sja-thedude. I really didn't know what you had in mind.

**Pull request merged**
